### PR TITLE
adding api for migrating from drupal module.

### PR DESCRIPTION
**Pull request by jmcclelland**
Here's a start. It turns out we don't have that many groups who have sync'ed with Cicero in the last few years, so I've stopped short of writing a comprehensive migration path (this one only migrates the main four fields).

Let me know what you think and if you have any suggestions.

### CODE REVIEW

**Comment by MegaphoneJon** [comment]
Hi Jamie - sorry, I don't know how I missed this!  I'll take a look.

**Comment by jmcclelland** [comment]
I've run this against one production site and the two problems are:

1. It is really really slow.
2. While it carefully avoids running twice on the same contact, it takes a long tiime to skip all the contacts it has already run against. (See point 1: it is really really slow).

I'm not entirely sure if it's worth it to try to fix these problems, but if you have any brilliant suggestions - maybe there is something simple I didn't think of.

**Comment by MegaphoneJon** [comment]
Right as you move into the foreach loop that iterates through contacts, you make two API calls - one to ensure they don't have existing Electoral v3 records, the other to pick up the city.

I think you could move that first API call out of the foreach loop.  Get yourself an array of IDs that shouldn't be updated.  You can even do a `NOT IN` parameter on your main Contact.get, so you never even look up those contacts.

Not having API4 available for your initial contact get makes things difficult.  I might split that into two API calls - one (API4) that returns everything but the custom fields, and a second API call (API3) to get the custom fields.  Then merge the results.  That way, you could get the city as part of the API4 call.

I think you could even merge the API4 call to get contact ID data with the API4 call that excludes contacts who are already migrated.  But that's pretty meager compared to removing the two `get` calls from the foreach loop.

I see you have Home address hard-coded as the address to look up.  You may want to use the migration script as a place to select that value from the Electoral API settings.

**Comment by MegaphoneJon** [comment]
Hi Jamie - having reviewed this code previously, and seeing as to how you're the primary user of it, I'm happy to merge it at this point.  Let me know if I shouldn't.

**Comment by jmcclelland** [comment]
Thanks Jon - I think you should merge it for now. 

I do plan to try your optimizing strategies, but it seems better to follow the publish early publish often mantra and maybe somebody else will be me to it.

I really under-estimated the work involved in transitioning from civicrm_cicero and my old petitionemail extension to electoral and Joseph's petition email code. I'm still in the research and planning phases so it might be a while before I'm ready to fully make the switch.

**Pull request merged**
